### ISSUE TITLE
Get rid of Google Analytics

### ISSUE THREAD

**Issue by nemanjaglumac** [AaruBama/memestr#48]
This is a Nostr project.
This is FOSS project.

You should strive to compose it using only FOSS libraries.
Google as a company and Nostr as an idea couldn't be further apart.

I'd say that you don't really need analytics in the early stages, but that's up to you.
If you decide that you absolutely need it, at least research some FOSS Google Analytics alternatives that respect privacy.

There should be plenty.

**Comment by nemanjaglumac** [comment]
The same goes for `web-vitals`, btw.
You're not using it anyway since all references to it are commented out.

**Comment by AaruBama** [comment]
Yes. Couldn't agree more.
Me and @abhay-raizada have had this discussion multiple times in past on how to get rid of GA and what to replace it with.
The other viable option we have is Open Web Analytics.

The only concern is it's way down the pipeline. There are some UI/UX fixes I have to do first for the large screen clients along with some major bug fixes.

**Comment by nemanjaglumac** [comment]
> The only concern is it's way down the pipeline.

You'll think about it when the time comes.
The best approach is to focus on one thing at a time. Start simple, execute well. Repeat :)

Good read:
https://www.martinfowler.com/bliki/Yagni.html
