### ISSUE TITLE
Optimize project for the open-source contributions [WIP]

### ISSUE THREAD

**Issue by nemanjaglumac** [AaruBama/memestr#52]
Every project can benefit from some essential prerequisites that make it more inviting, and easier to work with.
I'll try to list those essential steps in this issue.

> **Note**
> This is a WIP issue. Expect edits.

## 1. Documentation
What is the project about? How to contribute? How to build it? Can it be reused?
These are the question that should be answered in this section.
### 1.1 User-centric
- [ ] What is this project about. What sets it apart from similar projects and why should people use it.
- [x] Allow GitHub discussions

### 1.2 Developer-centric
- [ ] https://github.com/AaruBama/memestr/issues/51 (How to build and run the project)
- [ ] Add contributing guide
- [ ] Add security guide

### 1.3 Ops
- [ ] Introduce issue templates (explain how to best describe the issue)
- [ ] Introduce PR templates (explain how to best describe the issue)
- [ ] Edit the project description and set the link to the live app there

## 2. Clean code
Clean code makes it easier to onboard new developers.
- [x] https://github.com/AaruBama/memestr/pull/39
- [x] https://github.com/AaruBama/memestr/pull/40
- [x] https://github.com/AaruBama/memestr/pull/41
- [x] https://github.com/AaruBama/memestr/pull/47
- [ ] Remove unused and commented out code
 
## 3. Formatting rules and restrictions
Nobody likes to argue about "this" approach vs "that" approach. It's pointless, after all, and it is a huge waste of time.
The lack of formatting rules also makes diffs harder to read. Nobody cares about the whitespace changes.
Utilize tools that make all this fade into the background. Set and forget. Focus on writing code, and leave the formatting to the machine.
- [x] https://github.com/AaruBama/memestr/pull/43
- [x] https://github.com/AaruBama/memestr/pull/46
- [ ] Introduce explicit eslint rules (https://github.com/AaruBama/memestr/pull/54)
- [ ] Introduce CI checks that fail if code isn't formatted properly, or if some linting rules are broken (make this check required)

**Comment by AaruBama** [comment]
#62 fixes 1.1.
`Maybe allow GitHub discussions` , Sorry I didn't understand this part @nemanjaglumac

**Comment by AaruBama** [comment]
> https://github.com/features/discussions

Ah that. I've enabled the discussions. Maybe we can start with an announcement of latest release and contribution guidelines.
