### ISSUE TITLE
Use GitHub Actions to publish website updates

### ISSUE THREAD

**Issue by nemanjaglumac** [AaruBama/memestr#55]
GitHub Actions are perfect for website deployment, especially when you use GitHub pages.
Set up GHA to do this job on _____ (choose the trigger).

1. merge to master
    - It's risky to push directly to production (live app)
    - Set up staging - something like `demo.memestr.app`, or `staging.memestr.app` and push there
    - This can also be really good for testing and early feedback
2. manual trigger
    - Once you're sure things are working and you want to push an update, trigger an action that will push to production
    - Note: this can also be set to work on `tag`, which might help you if you decide to version releases

**Comment by AaruBama** [comment]
Sounds good. We can have a staging domain up that could point to a github-page and have dedicated staging branch for testing deployments before making final release.

We can set GHA on merge to qa and a manual trigger for production deployment.
