### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by abhay-raizada** [AaruBama/memestr#66]
Would be clearer to the devs contributing to the project as to how their code is being used and how it can be further used. Lmk what you think @rakesh-verma-16 @nemanjaglumac .

Personally, I prefer the [MIT LIcense.](https://opensource.org/license/mit/).

**Comment by nemanjaglumac** [comment]
100%!
Don't know how I missed it in https://github.com/AaruBama/memestr/issues/52. That's one of the main things every OSS project must have.

**Comment by AaruBama** [comment]
@abhay-raizada @nemanjaglumac LMK if it looks good, I'll merge it.
Would also be mergine some other PRs tonight.

**Comment by AaruBama** [comment]
Merged the PR. Feel free to reopen if needs any update.
